volumes:
  pg_data:

networks:
  app_net:
    driver: bridge

services:
  db:
    image: postgres:17
    container_name: resume_db
    restart: always
    networks:
      - app_net
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: insparation06/resume_backend
    container_name: resume_backend
    restart: on-failure
    networks:
      - app_net
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: insparation06/resume_frontend
    container_name: resume_frontend
    networks:
      - app_net

  gateway:
    image: insparation06/resume_gateway
    container_name: resume_gateway
    networks:
      - app_net
    ports:
      - 8000:80