name: Main Resume Service workflow

on:
  push:
    branches:
      - main
jobs:
  Build_Backend_and_Push_to_docker_hub:
    name: Push Backend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: insparation06/resume_backend:latest
  Build_Frontend_and_push_to_docker_hub:
    name: Push Frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: insparation06/resume_frontend:latest
  Build_Gateway_and_push_to_docker_hub:
    name: Push Gateway Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./gateway/
          push: true
          tags: insparation06/resume_gateway:latest
  Deploy_Project:
    runs-on: ubuntu-latest
    needs:
      - Build_Backend_and_Push_to_docker_hub
      - Build_Frontend_and_push_to_docker_hub
      - Build_Gateway_and_push_to_docker_hub
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "docker-compose.yml"
        target: "resume_service"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd resume_service
          sudo docker compose pull
          sudo docker compose down
          sudo docker compose up -d
          sudo docker compose exec -it backend alembic upgrade head
  Send_message_to_Telegram:
    runs-on: ubuntu-latest
    needs: Deploy_Project
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой Resume Service успешно выполнен!
